services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: usermgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - go-user-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      timeout: 5s
      retries: 5

  go-user:
    build:
      context: ./api/
      args:
        - VERSION=${VERSION}
        - DB_HOST=${DB_HOST}
    image: go-user:${VERSION}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      args:
        - PORT=${PORT}
        - VERSION=${VERSION}
        - PROXY_HOST=${PROXY_HOST}
    image: nginx-proxy:${VERSION}
    depends_on:
      - go-user
    ports:
      - 80:80

  dbeaver:
    container_name: dbeaver_container
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "8081:8978"
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
volumes:
  go-user-db:
    driver: local
