version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: usermgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - go-user-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
      
  go-user:
    build:
      context: ./api/
      args:
        - VERSION=${VERSION}
        - PORT=${PORT}
    image: go-user:${VERSION}
    ports:
      - ${PORT}:${PORT}

  nginx-proxy:
    build:
      context: ./nginx-proxy/
      args:
        - service=${SERVICE}
        - port=${PORT}
        - VERSION=${VERSION}
    image: nginx-proxy:${VERSION}
    ports:
      - 80:80

  dbeaver:
    container_name: dbeaver_container
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "8081:8978"
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace

volumes:
  go-user-db:
    driver: local
